[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/public/courts"
  to = "/.netlify/functions/courts"
  status = 200

[[redirects]]
  from = "/api/public/players"
  to = "/.netlify/functions/players"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200