name: Vercel Dispatch Test

on:
  repository_dispatch:
    types:
      - 'vercel.deployment.ready'
      - 'vercel.deployment.success'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Log event
      run: |
        echo "Event received: ${{ github.event.action }}"
        echo "Environment: ${{ github.event.client_payload.environment }}"
        echo "URL: ${{ github.event.client_payload.url }}"
